---
title: "Time-lagged prediction for daily cigarette usage"
author:
  - Jeung-Hyun Lee
date: "`r Sys.Date()`"
output: 
  pdf_document: 
    number_sections: yes
    latex_engine: xelatex
    keep_tex: yes
editor_options:
  chunk_output_type: console
header-includes:
- \usepackage{kotex}
- \usepackage{float}
- \usepackage{booktabs}
- \usepackage{colortbl}
- \usepackage{makecell}
- \usepackage{pdflscape}
- \newcommand{\blandscape}{\begin{landscape}}
- \newcommand{\elandscape}{\end{landscape}}
---

```{r setup, include=FALSE}
# Reset workspace
rm(list = ls())
setwd("~/Github/SmokingPred_ADO")

# For plotting
library(tidyverse)
library(lubridate)
library(cowplot)
library(latex2exp)

# For summary and tables
library(gtsummary)
library(kableExtra)

# For modeling
library(lme4)
library(lmerTest)
library(glmnet)
library(MuMIn)
library(rsq)
library(r2glmm)
library(splitTools)
library(corrplot)

library(ggcorrplot)
library(Hmisc)

knitr::opts_chunk$set(
  echo = FALSE, message = FALSE, warning = FALSE,
  fig.align = 'center', dpi = 300, out.width = '\\textwidth')
```

```{r globals}
FILE_DATA <- file.path('.', 'data')

MAP_LABEL_SURVEY <- list(
  "Q51"   = "has_used_cigar",
  "Q52"   = "has_used_ecigar",
  "Q1"    = "Usage",
  "Q1p"   = "Usage",
  "lgQ1p" = "Log usage",
  "Q53"   = "usage_ecigar",
  "Q2"    = "Craving",
  "Q3"    = "Mood",
  "Q4"    = "sleep_problem",
  "Q5"    = "troubles_with_family_friends",
  "Q6"    = "Stress",
  "Q7"    = "Depression",
  "Q8"    = "Anxiety",
  "Q9"    = "hobby",
  "Q10"   = "time_with_family_friends",
  "Q11"   = "religion",
  "Q30"   = "Medication"
)

MAP_LABEL_PARAM <- list(
  alpha = '$\\alpha$',
  beta = '$-\\beta$',
  logk = 'log k'
)

MAP_LABEL_DEMO <- list(
  age = 'Age',
  sex = 'Sex',
  sexFemale = 'Sex (Female)',
  day = 'Day',
  subject = 'Subject'
)

MAP_LABEL <- c(MAP_LABEL_SURVEY, MAP_LABEL_PARAM, MAP_LABEL_DEMO)

IV_SURVEY <- c('Q1', 'Q2', 'Q3', 'Q6', 'Q7', 'Q8', 'Q30') 
IV_PARAM <- c('alpha', 'beta', 'logk')
IV_DEMO <- c('age', 'sex')

CRIT_DAYS = 14
```

```{r load_data}
df_daily <- 
  read_tsv(paste0(FILE_DATA, '/a1_daily.tsv'), show_col_types = FALSE)
```

```{r functions}
make_formula <- function(dv, ivs_fixed, ivs_random = NULL) {
  eqn <- str_c(dv, ' ~ ')
  
  if (is.null(ivs_fixed)) {
    eqn <- str_c(eqn, '1')
  } else {
    eqn <- str_c(eqn, paste(ivs_fixed, collapse = ' + '))
  }
  
  if (!is.null(ivs_random)) {
    eqn <- str_c(
      eqn, ' + ',
      paste(str_c('(1 | ', ivs_random, ')'), collapse = ' + ')
    )
  }
  
  as.formula(eqn)
}

get_r2_marg_cond <- function(mod) {
  if (any(class(mod) == 'lm')) {
    return(list(marg = rsq(mod), cond = rsq(mod)))
  }
  
  # Zhang, D. (2020). Coefficients of determination for mixed-effects models. arXiv:2007.0867.
  fit <- rsq::rsq(mod)
  list(marg = fit$fixed, cond = fit$model)
  
  # Nakagawa, S., Schielzeth, H. (2013) A general and simple method for obtaining R² from Generalized Linear Mixed-effects Models. Methods in Ecology and Evolution 4: 133–142
  # fit <- r.squaredGLMM(mod)
  # list(marg = fit[1], cond = fit[2])
}

run_model <- function(data, config) {
  fml <- make_formula(config$dv, config$ivs_fixed, config$ivs_random)
  
  is_glm <- (config$model_name %in% c('GLM', 'GLMM'))
  model_func <- switch(
    config$model_name, LM = lm, GLM = glm, LMM = lmer, GLMM = glmer)
  
  if (!is_glm) {
    mod <- model_func(formula = fml, data = data)
  } else {
    mod <- model_func(formula = fml, data = data, family = config$model_family)
  }
  
  if (config$exclude_outliers) {
    model_subset <- cooks.distance(mod) < (4 / nrow(data))
    data_subset <- data[model_subset,]
    
    if (!is_mod_glm) {
      mod <- model_func(formula = fml, data = data_subset)
    } else {
      mod <- model_func(formula = fml, data = data_subset, family = config$model_family)
    }
    
    return(list(data = data_subset, fml = fml, mod = mod))
  }
  
  return(list(data = data, fml = fml, mod = mod))
}

get_label_for_term <- function(term) {
  tt <- term %>% str_remove('_next') %>% str_remove('_curr')
  ret <- MAP_LABEL[tt] %>% unlist %>% unname
  ret
}

get_label_for_term_wo <- function(term) {
  tt <- term %>% str_remove('_curr')
  ret <- MAP_LABEL[tt] %>% unlist %>% unname
  ret
}

calculate_r2 <- function (y, y_hat) {
  1 - sum((y - y_hat) ** 2, na.rm = TRUE) / sum((y - mean(y, na.rm = TRUE)) ** 2, na.rm = TRUE)
}

calculate_mse <- function (y, y_hat) {
  mean((y - y_hat) ** 2)
}

# here
draw_coef_figure <- function(mod, title = NULL, custom_order=NULL) {
  smr <- summary(mod)
  subtitle <- NA
  if (any(class(mod) == 'glm')) {
    r2 <- MuMIn::r.squaredGLMM(mod)
    subtitle <- 
      sprintf("$R^2$ = $%.3f$", r2[1]) %>%
      TeX()
  } else if (class(mod) == 'lm') {
    subtitle <- 
      sprintf("$R^2$ = $%.3f$, Adjusted $R^2$ = $%.3f$",
              smr$r.squared, smr$adj.r.squared) %>%
      TeX()
  } else {
    r2 <- get_r2_marg_cond(mod)
    subtitle <-
      sprintf("$R^2_{fixed}$ = $%.3f$, $R^2_{total}$ = $%.3f$",
              r2$marg, r2$cond) %>%
      TeX()
  }
  
  df_coef <-
    smr$coefficients %>%
    as.data.frame() %>%
    rownames_to_column('term') %>%
    as_tibble() %>%
    rename(estimate = Estimate,
           std.error = `Std. Error`) %>%
    rename_at(vars(starts_with('Pr(>')), function(v) 'p.value') %>%
    filter(term != '(Intercept)') %>%
    mutate(
      term = factor(
        term,
        levels = if (!is.null(custom_order)) custom_order else term %>% rev,
        labels = if (!is.null(custom_order)) custom_order else get_label_for_term(term) %>% rev
      ),
      ci_lower = estimate - 1.96 * std.error,
      ci_upper = estimate + 1.96 * std.error,
      is_sig = ifelse(ci_lower > 0, 1, ifelse(ci_upper < 0, -1, 0)),
      is_sig = as.character(is_sig)
    )
  
  p_coef <-
    df_coef %>%
    ggplot(aes(x = term, y = estimate, color = is_sig)) +
    geom_hline(yintercept = 0, colour = "grey60", linetype = 2) +
    geom_errorbar(aes(ymin = ci_lower, ymax = ci_upper), width = 0) +
    geom_point(size = 3) +
    labs(y = "Beta estimate",
         title = title, 
         subtitle = subtitle) +
    scale_color_manual(values = c("1" = "red", "0" = "#666666", "-1" = "blue")) +
    # scale_x_discrete(labels = TeX(as.character(df_coef$term))) +
    coord_flip() +
    theme_bw() +
    theme(legend.position = "none",
          axis.title.y = element_blank(),
          axis.text.y = element_text(size = 11, hjust = 1, color = 'black'),
          plot.title = element_text(face = "bold", hjust = 0.5),
          plot.subtitle = element_text(hjust = 0.5))
  
  p_coef
}

draw_figure <- function(data, config, mod, y_label, title) {
  smr <- summary(mod)
  
  is_lmm <- !any(class(mod) == 'lm')
  
  y_pred <- predict(mod, newdata = data, type = 'response', allow.new.levels = TRUE)
  if (!is_lmm) {
    y_link <- y_pred
  } else {
    y_link <- predict(mod, newdata = data, type = 'link', allow.new.levels = TRUE)
  }
  y_true <- data %>% pull(!!as.name(y_label))
  y_resi <- scale(y_true - y_pred) %>% unname %>% as.vector()
  
  custom_order <- c(# "sexFemale", "age", 
                  "alpha_curr", "beta_curr", "logk_curr", 
                  "Q2_curr", "Q3_curr", "Q6_curr", "Q8_curr", 
                  "Q7_curr", "Q1_curr", "Q30_curr", "day", "(Intercept)")
  
  dat_fixed <- 
    data %>%
      dplyr::select(all_of(config$ivs_fixed)) %>%
      mutate(`(Intercept)` = 1) %>%
      select(all_of(custom_order)) %>% 
      # dplyr::select(`(Intercept)`, everything()) %>% 
      as.matrix
  
  coef_fixed <-
    smr$coefficient %>%
    as.data.frame() %>%
    rownames_to_column('variable') %>%
    dplyr::select(variable, Estimate) %>%
    mutate(variable = factor(variable, levels = custom_order)) %>%
    arrange(variable) %>% 
    column_to_rownames('variable') %>% 
    as.matrix# as.vector
  
  y_fixed <-
    config$model_family$linkinv(dat_fixed %*% as.matrix(coef_fixed)) %>%
    unname %>%
    as.vector
  
  df_pred <-
    data %>%
    mutate(y_pred = y_pred,
           y_true = !!as.name(y_label),
           y_link = y_link,
           y_pred_fixed = y_fixed,
           y_resi = y_resi) %>%
    dplyr::select(subject, day_orig, y_pred, y_pred_fixed, y_true, y_link, y_resi)
  
  
  p_coef <-
    draw_coef_figure(mod, '', custom_order) +
    theme(plot.title = element_blank())
  
  p_pred_day <-
    df_pred %>%
    # filter(subject %in% c("SMO21302")) %>% 
    # filter(subject %in% c("SMO19509", "SMO19301", "SMO19306", "SMO22104", "SMO22208",
    #                       "SMO22209", "SMO22201", "SMO22302", "SMO21402", "SMO22506")) %>%  # var
    filter(subject %in% c("SMO19403", "SMO19407", "SMO19408", "SMO19412", "SMO21104",
                          "SMO21303", "SMO21302", "SMO22408", "SMO22401", "SMO22307")) %>%  # stab
    dplyr::select(day_orig, y_pred, y_true, y_pred_fixed) %>%
    (function(ddd) {
      if (!is_lmm) {
        return(ddd %>% dplyr::select(-c(y_pred_fixed)))
      }
      
      ddd
    }) %>%
    gather(variable, value, -day_orig) %>%
    group_by(day_orig, variable) %>%
    mutate(value = mean(value),
           se = sd(value) / sqrt(n() - 1)) %>%
    ggplot(aes(x = day_orig, y = value, color = variable)) +
    geom_line(aes(color = variable, linetype = variable)) +
    # geom_point(aes(color = variable)) +
    # coord_cartesian(ylim = c(0, NA)) +
    coord_cartesian(ylim = c(0, 12)) +
    scale_color_manual(
      values = c(y_pred = '#D1495B', y_pred_fixed = '#66A182', y_true = '#8D96A3'),
      labels = TeX(c(
        y_pred = '$Y_{pred}$',
        y_pred_fixed = '$Y_{pred}^{(fixed)}$',
        y_true = '$Y_{true}$'
      )),
      drop = TRUE
    ) +
    scale_linetype_manual(
      values = c(y_pred = 'solid', y_pred_fixed = 'solid', y_true = 'longdash'),
      labels = TeX(c(
        y_pred = '$Y_{pred}$',
        y_pred_fixed = '$Y_{pred}^{(fixed)}$',
        y_true = '$Y_{true}$'
      )),
      drop = TRUE
    ) +
    labs(x = 'Day', y = 'cigarettes consumed') +
    guides(color = guide_legend(nrow = 1)) +
    theme_bw() +
    theme(legend.title = element_blank(),
          legend.position = c(0.50, 0.85),
          legend.background = element_blank())
  
  p_resi <-
    df_pred %>%
    ggplot(aes(x = y_pred, y = y_resi)) +
    geom_hline(yintercept = 0) +
    geom_jitter(alpha = 0.25, width = 0.25, shape = 1) +
    labs(x = TeX('$Y_{pred}$'), y = 'Residual') +
    theme_bw()
  
  y_range <- c(
    min(df_pred$y_true, df_pred$y_pred),
    max(df_pred$y_true, df_pred$y_pred)
  )
  
  p_qq <-
    df_pred %>%
    ggplot(aes(sample = y_resi)) +
    geom_qq(shape = 1) +
    stat_qq_line() +
    labs(x = 'Theoretical normal quantiles',
         y = 'Sample residual quantiles') +
    theme_bw()
  
  cor_fit <- cor.test(df_pred$y_pred, df_pred$y_true)
  if (cor_fit$p.value < 0.001) {
    label_cor <- TeX(sprintf(
      "Pearson's $r = %.3f$ ($p < 0.001$)",
      cor_fit$estimate
    ))
  } else {
    label_cor <- TeX(sprintf(
      "Pearson's $r = %.3f$ ($p = %.3f$)",
      cor_fit$estimate, cor_fit$p.value
    ))
  }
  
  p_pred_true <-
    df_pred %>%
    ggplot(aes(x = y_true, y = y_pred)) +
    geom_abline(slope = 1, intercept = 0) +
    geom_point(alpha = 0.25, shape = 1) +
    geom_smooth(method = 'lm') +
    coord_cartesian(xlim = y_range, ylim = y_range) +
    labs(subtitle = label_cor,
         x = TeX('$Y_{true}$'),
         y = TeX('$Y_{pred}$')) +
    theme_bw()
  
  p_title <-
    ggdraw() + 
    draw_label(
      title,
      fontface = 'bold',
      x = 0,
      hjust = 0
    ) +
    theme(
      # add margin on the left of the drawing canvas,
      # so title is aligned with left edge of first plot
      plot.margin = margin(0, 0, 0, 7)
    )
  
  # plot_grid(
  #   p_title,
  plot_grid(
    p_coef,
    plot_grid(
      p_pred_day,
      # p_resi,
      NULL,
      ncol = 1, align = 'v'
    ),
    nrow = 1
  )
}
```

```{=html}
<!-- -->
```

```{r}
p_coef <-
  df_coef %>%
    ggplot(aes(x = term, y = estimate, color = is_sig)) +
    geom_hline(yintercept = 0, colour = "grey60", linetype = 2) +
    geom_errorbar(aes(ymin = ci_lower, ymax = ci_upper), width = 0) +
    geom_point(size = 3) +
    labs(y = "Beta estimate", 
         # title = title, 
         subtitle = subtitle) +
    scale_color_manual(values = c("1" = "red", "0" = "#666666", "-1" = "blue")) +
    scale_x_discrete(labels = TeX(as.character(df_coef$term))) +
    coord_flip() +
    theme_bw() +
    theme(legend.position = "none",
          axis.title.y = element_blank(),
          axis.text.y = element_text(size = 11, hjust = 1, color = 'black'),
          plot.title = element_text(face = "bold", hjust = 0.5),
          plot.subtitle = element_text(hjust = 0.5))  
```

\pagebreak

# Model comparison

```{r setup_cv}
CV_K <- 3
CV_REP <- 100
```

```{r functions_cv}
run_model_with_loocv <- function(data, config) {
  fml <- make_formula(config$dv, config$ivs_fixed, config$ivs_random)
  
  # Make a dataset to use
  data_all <-
    data %>%
    dplyr::select(all_of(c(config$dv, config$ivs_fixed, config$ivs_random)), day_orig) %>%
    drop_na()
  
  is_glm <- (config$model_name %in% c('GLM', 'GLMM'))
  model_func <- switch(
    config$model_name, LM = lm, GLM = glm, LMM = lmer, GLMM = glmer)
  
  # Fit a model with the whole dataset
  if (!is_glm) {
    mod_all <- model_func(formula = fml, data = data_all)
  } else {
    mod_all <- model_func(formula = fml, data = data_all, family = config$model_family)
  }
  
  # Run leave-one-out cross-validation (LOOCV)
  folds <- create_folds(data %>% pull(subject), type = 'stratified',
                        k = CV_K, m_rep = CV_REP)
  fit_r2_train <- c()
  fit_r2_test <- c()
  fit_mse_train <- c()
  fit_mse_test <- c()
  
  for (fold in folds) {
    data_train <- data_all[fold,]
    data_test  <- data_all[-fold,]
    
    if (!is_glm) {
      mod <- model_func(formula = fml, data = data_train)
    } else {
      mod <- model_func(formula = fml, data = data_train, family = config$model_family)
    }
    
    y_true_train <- data_train %>% pull(all_of(config$dv))
    y_pred_train <- predict(mod, newdata = data_train, type = 'response') %>% as.vector %>% unname
    y_true_test <- data_test %>% pull(all_of(config$dv))
    y_pred_test <- predict(mod, newdata = data_test, type = 'response') %>% as.vector %>% unname
    
    fit_r2_train <- c(fit_r2_train, calculate_r2(y_true_train, y_pred_train))
    fit_r2_test <- c(fit_r2_test, calculate_r2(y_true_test, y_pred_test))
    fit_mse_train <- c(fit_mse_train, calculate_mse(y_true_train, y_pred_train))
    fit_mse_test <- c(fit_mse_test, calculate_mse(y_true_test, y_pred_test))
  }
  
  list(
    data = data_all,
    config = config,
    fml = fml,
    mod = mod_all,
    cv = list(
      r2_train = fit_r2_train, r2_test = fit_r2_test,
      mse_train = fit_mse_train, mse_test = fit_mse_test
    )
  )
}
```

```{r configs}
configs_mod <- list(
  list(
    model_family = gaussian(),
    model_name = 'LMM'
  ),
  NULL
)

configs_ivs_fixed <- list(
  list(ivs_fixed = c()),
  list(ivs_fixed = c(str_c(IV_PARAM[1], '_curr'))),
  list(ivs_fixed = c(str_c(IV_PARAM[1], '_curr'), 'day')),
  list(ivs_fixed = c(str_c(IV_PARAM[2], '_curr'))),
  list(ivs_fixed = c(str_c(IV_PARAM[2], '_curr'), 'day')),
  list(ivs_fixed = c(str_c(IV_PARAM[3], '_curr'))),
  list(ivs_fixed = c(str_c(IV_PARAM[3], '_curr'), 'day')),
  list(ivs_fixed = c(str_c(IV_PARAM, '_curr'))),
  list(ivs_fixed = c(str_c(IV_PARAM, '_curr'), 'day')),
  list(ivs_fixed = c(str_c(IV_SURVEY[1], '_curr'))),
  list(ivs_fixed = c(str_c(IV_SURVEY[1], '_curr'), 'day')),
  list(ivs_fixed = c(str_c(c(IV_SURVEY[1], IV_PARAM[1]), '_curr'))),
  list(ivs_fixed = c(str_c(c(IV_SURVEY[1], IV_PARAM[1]), '_curr'), 'day')),
  list(ivs_fixed = c(str_c(c(IV_SURVEY[1], IV_PARAM[2]), '_curr'))),
  list(ivs_fixed = c(str_c(c(IV_SURVEY[1], IV_PARAM[2]), '_curr'), 'day')),
  list(ivs_fixed = c(str_c(c(IV_SURVEY[1], IV_PARAM[3]), '_curr'))),
  list(ivs_fixed = c(str_c(c(IV_SURVEY[1], IV_PARAM[3]), '_curr'), 'day')),
  list(ivs_fixed = c(str_c(IV_SURVEY[1:2], '_curr'))),
  list(ivs_fixed = c(str_c(IV_SURVEY[1:2], '_curr'), 'day')),
  list(ivs_fixed = c(str_c(c(IV_SURVEY[1:2], IV_PARAM), '_curr'))),
  list(ivs_fixed = c(str_c(c(IV_SURVEY[1:2], IV_PARAM), '_curr'), 'day')),
  list(ivs_fixed = c(str_c(IV_SURVEY, '_curr'))),
  list(ivs_fixed = c(str_c(IV_SURVEY[1:6], '_curr'))),
  list(ivs_fixed = c(str_c(IV_SURVEY[1:6], '_curr'), 'day')),
  list(ivs_fixed = c(str_c(IV_SURVEY, '_curr'), 'day')),
  list(ivs_fixed = c(str_c(c(IV_SURVEY[1:6], IV_PARAM), '_curr'))),
  list(ivs_fixed = c(str_c(c(IV_SURVEY, IV_PARAM), '_curr'))),
  list(ivs_fixed = c(str_c(c(IV_SURVEY[1:6], IV_PARAM), '_curr'), 'day')),
  list(ivs_fixed = c(str_c(c(IV_SURVEY, IV_PARAM), '_curr'), 'day'))
)

configs_ivs_random <- list(
  list(ivs_random = c()),
  list(ivs_random = c('subject'))
)

CONFIGS <-
  lapply(configs_mod, function(c_m) {
    if (is.null(c_m)) {
      return(NULL)
    }
    
    lapply(configs_ivs_random, function(c_ir) {
      is_lmm <- c_m$model_name %in% c('LMM', 'GLMM')
      has_rand_eff <- any(!is.null(c_ir$ivs_random))
      
      if (xor(is_lmm, has_rand_eff)) {
        return(NULL)
      } 
      
      lapply(configs_ivs_fixed, function(c_if) {
        c(
          list(
            dv = str_c(IV_SURVEY[1], '_next'),
            exclude_outliers = FALSE
          ),
          c_m,
          c_if,
          c_ir
        )
      })
    }) %>%
      do.call(what = c)
  }) %>%
  do.call(what = c) %>%
  (function(lc) {
    lc[sapply(lc, function(x) !is.null(x))]
  })
```

```{r run_cv}
fn_cache <- './data/cvfits_time-lagged_with_med.RData'

if (!file.exists(fn_cache) || TRUE) {
  df_cv <- NULL
  cvfits <- list()
  
  for (i in 1:length(CONFIGS)) {
    config <- CONFIGS[[i]]
    cvfits[[i]] <- run_model_with_loocv(df_daily, config)
    
    df_cv <- bind_rows(
      df_cv,
      tibble(
        idx = i,
        model_name = config$model_name,
        model_desc = ifelse(is.null(config$model_desc), '', config$model_desc),
        dv = config$dv,
        ivs_fixed = paste(get_label_for_term(config$ivs_fixed), collapse = ', '),
        ivs_random = paste(get_label_for_term(config$ivs_random), collapse = ', '),
        r2_train = mean(cvfits[[i]]$cv$r2_train),
        mse_train = mean(cvfits[[i]]$cv$mse_train),
        r2_test = mean(cvfits[[i]]$cv$r2_test),
        mse_test = mean(cvfits[[i]]$cv$mse_test)
      )
    )
  }
  save(cvfits, df_cv, file = fn_cache)
} else {
  load(fn_cache)
}

```

```{r}

cvfit_best <- cvfits[[idx_best]]
config_best <- cvfit_best$config
mod <- cvfit_best$mod
smr <- summary(mod)

smr$coefficient %>%
    as.data.frame() %>%
    rownames_to_column('variable') %>%
    dplyr::select(variable, Estimate) %>%
    mutate(variable = factor(variable, levels = custom_order)) %>%
    arrange(variable) %>% 
    column_to_rownames('variable')

best_model <- lmer(Q1_next ~  alpha_curr + beta_curr + logk_curr + Q1_curr + Q2_curr + Q3_curr + Q6_curr + Q7_curr + Q8_curr + Q30_curr + day + (1 | subject), data = df_daily)
sum_best_model <- summary(best_model)
MuMIn::r.squaredGLMM(best_model)
r2 <- get_r2_marg_cond(best_model)
subtitle <-
  sprintf("$R^2_{fixed}$ = $%.3f$, $R^2_{total}$ = $%.3f$",
          r2$marg, r2$cond) %>%
  TeX()

df_coef <-
  sum_best_model$coefficients %>%
    as.data.frame() %>%
    rownames_to_column('term') %>%
    as_tibble() %>%
    rename(estimate = Estimate,
           std.error = `Std. Error`) %>%
    rename_at(vars(starts_with('Pr(>')), function(v) 'p.value') %>%
    filter(term != '(Intercept)') %>%
    mutate(
      term = factor(
        term,
        levels = term %>% rev, 
        labels = get_label_for_term(term) %>% rev
      ),
      ci_lower = estimate - 1.96 * std.error,
      ci_upper = estimate + 1.96 * std.error,
      is_sig = ifelse(ci_lower > 0, 1, ifelse(ci_upper < 0, -1, 0)),
      is_sig = as.character(is_sig)
    )
  
p_coef <-
  df_coef %>%
    ggplot(aes(x = term, y = estimate, color = is_sig)) +
    geom_hline(yintercept = 0, colour = "grey60", linetype = 2) +
    geom_errorbar(aes(ymin = ci_lower, ymax = ci_upper), width = 0) +
    geom_point(size = 3) +
    labs(y = "Beta estimate", 
         # title = title, 
         subtitle = subtitle) +
    scale_color_manual(values = c("1" = "red", "0" = "#666666", "-1" = "blue")) +
    scale_x_discrete(labels = TeX(as.character(df_coef$term))) +
    coord_flip() +
    theme_bw() +
    theme(legend.position = "none",
          axis.title.y = element_blank(),
          axis.text.y = element_text(size = 11, hjust = 1, color = 'black'),
          plot.title = element_text(face = "bold", hjust = 0.5),
          plot.subtitle = element_text(hjust = 0.5))


```


```{r}
# regressing out usage variable 
# autocorrelation analysis
# step 1: Regress usage on t+1 on t
model1 <- lm(Q1p_next ~ Q1_curr, data = df_daily)
df_daily$residuals <- residuals(model1)

# step 2: Use residuals in the mixed-effect model
# Q2: craving
# Q3: mood
# Q6: stress
# Q7: depression
# Q8: anxiety
# Q30: medication 
model2 <- lmer(residuals ~  alpha_curr + beta_curr + logk_curr + Q2_curr + Q3_curr + Q6_curr + Q7_curr + Q8_curr + Q30_curr + day + (1 | subject), data = df_daily)
sum_model2 <- summary(model2)
MuMIn::r.squaredGLMM(model2)
r2 <- get_r2_marg_cond(model2)
subtitle <-
  sprintf("$R^2_{fixed}$ = $%.3f$, $R^2_{total}$ = $%.3f$",
          r2$marg, r2$cond) %>%
  TeX()

df_coef <-
  sum_model2$coefficients %>%
    as.data.frame() %>%
    rownames_to_column('term') %>%
    as_tibble() %>%
    rename(estimate = Estimate,
           std.error = `Std. Error`) %>%
    rename_at(vars(starts_with('Pr(>')), function(v) 'p.value') %>%
    filter(term != '(Intercept)') %>%
    mutate(
      term = factor(
        term,
        levels = term %>% rev, 
        labels = get_label_for_term(term) %>% rev
      ),
      ci_lower = estimate - 1.96 * std.error,
      ci_upper = estimate + 1.96 * std.error,
      is_sig = ifelse(ci_lower > 0, 1, ifelse(ci_upper < 0, -1, 0)),
      is_sig = as.character(is_sig)
    )
  
p_coef <-
  df_coef %>%
    ggplot(aes(x = term, y = estimate, color = is_sig)) +
    geom_hline(yintercept = 0, colour = "grey60", linetype = 2) +
    geom_errorbar(aes(ymin = ci_lower, ymax = ci_upper), width = 0) +
    geom_point(size = 3) +
    labs(y = "Beta estimate", 
         # title = title, 
         subtitle = subtitle) +
    scale_color_manual(values = c("1" = "red", "0" = "#666666", "-1" = "blue")) +
    scale_x_discrete(labels = TeX(as.character(df_coef$term))) +
    coord_flip() +
    theme_bw() +
    theme(legend.position = "none",
          axis.title.y = element_blank(),
          axis.text.y = element_text(size = 11, hjust = 1, color = 'black'),
          plot.title = element_text(face = "bold", hjust = 0.5),
          plot.subtitle = element_text(hjust = 0.5))



```


```{r}
idx_best <- df_cv %>% filter(mse_test == min(mse_test)) %>% pull(idx)

df_cv %>%
  mutate(d_mse_train = mse_train - min(mse_train),
         d_mse_test = mse_test - min(mse_test)) %>%
  dplyr::select(idx, ivs_fixed,
         r2_train, mse_train, d_mse_train,
         r2_test, mse_test, d_mse_test) %>%
  kable(format = 'latex', booktabs = TRUE, digits = 3, escape = FALSE, linesep = '', 
        col.names = c(
          "\\#", "IV$_\\text{fixed}$",
          "$R^2$", "MSE", "$\\Delta$MSE",
          "$R^2$", "MSE", "$\\Delta$MSE"
        ),
        caption = str_glue("Model comparison results of {CV_K}-fold cross validation with {CV_REP} repetitions.")) %>%
  kable_styling(font_size = 10, latex_options = c('HOLD_position')) %>%
  add_header_above(c(" " = 2, "Train" = 3, "Test" = 3)) %>%
  row_spec(idx_best, background = 'yellow') %>%
  footnote(
    general = str_c(
      "All models included subject as a random effect."
    )
  ) %>%
  landscape()


# for html display
df_cv %>%
  mutate(d_mse_train = mse_train - min(mse_train),
         d_mse_test = mse_test - min(mse_test)) %>%
  dplyr::select(idx, ivs_fixed,
         r2_train, mse_train, d_mse_train,
         r2_test, mse_test, d_mse_test) %>%
  kable(format = 'html', digits = 3, escape = FALSE, 
        col.names = c(
          "#", "IV_fixed",
          "R² (Train)", "MSE (Train)", "ΔMSE (Train)",
          "R² (Test)", "MSE (Test)", "ΔMSE (Test)"
        ),
        caption = str_glue("Model comparison results of {CV_K}-fold cross validation with {CV_REP} repetitions.")) %>%
  kable_styling(font_size = 10, full_width = FALSE) %>%
  add_header_above(c(" " = 2, "Train" = 3, "Test" = 3)) %>%
  row_spec(idx_best, background = '#FFFFA7') %>%
  footnote(
    general = "All models included subject as a random effect."
  ) 

```

## Best model
# this is the coefficient plot 

```{r, fig.width = 8, fig.height = 4, out.width = '.8\\textwidth'}
cvfit_best <- cvfits[[idx_best]]
config_best <- cvfit_best$config

draw_figure(
  cvfit_best$data,
  config_best,
  cvfit_best$mod,
  config_best$dv,
  sprintf(
    'Model %d: %s %s\n%s',
    idx_best, config_best$model_name,
    ifelse(!is.null(config_best$model_desc), str_c('- ', config_best$model_desc), ''),
    paste(format(cvfit_best$fml), collapse = '\n')
  )
)


```
